### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by marygibeau** [Microsoft/windows-admin-center-extension-template#13]
After running the WAC create command there were some issues in the strings.ts file from a dash in the resjason file. It was resolved by removing the "-" in the company title. The "-" didn't need to be removed from the section title ("//:" "Test-Feature" was fine).

ex. "Test-Feature_title" => "TestFeature_title"

**Comment by mattatmsft** [comment]
Thanks for pointing this out.  Fixed in 0.1.9.
